# Generated by Django 5.0.8 on 2025-07-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothes/')),
                ('clothing_type', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('outerwear', 'Outerwear')], max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('style', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('sports', 'Sports')], max_length=20)),
                ('feature_vector', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
