# Generated by Django 5.2.4 on 2025-07-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
