# Generated by Django 5.2.4 on 2025-07-11 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_alter_clothingitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='color',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='color_palette',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='mary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
