# Generated by Django 5.2.4 on 2025-07-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_remove_clothingitem_color_clothingitem_color_palette_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='mary_color',
            new_name='primary_color',
        ),
    ]
