# Generated by Django 5.2.4 on 2025-07-29 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_rename_mary_color_clothingitem_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='clothing_type',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Shoes', 'Shoes'), ('Outerwear', 'Outerwear')], max_length=20),
        ),
    ]
