# Generated by Django 5.2.4 on 2026-07-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_clothingitem_user_alter_clothingitem_clothing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Shoes', 'Shoes'), ('Outerwear', 'Outerwear')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
